/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nustana;
import backendless.BackendlessClient;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
import org.json.JSONArray;
import tools.UI;
/**
 *
 * @author saifu
 */
public class OrderWindow extends javax.swing.JFrame {
    private String price;
       public OrderWindow(String itemName , String price ) {
        try{
        JSONArray array = NUSTANA.getClient().GetObjects("Items","shopId='" + NewOrderInfo.getShopId() + "' and name='" + itemName + "'");
        JSONObject obj = array.getJSONObject(0);
        NewOrderInfo.setItemId(obj.getString("objectId"));
         initComponents();
         this.price=price;
        this.totalPrice.setText("Total= Rs.");
         this.itemName.setText(itemName);
         this.priceDisplay.setText("Price= "+price);
    }
        catch(Exception e){
            UI.ErrMsg("Error loading window", "Window loading error");
        }
       }
       
 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemCount = new javax.swing.JSpinner();
        address = new javax.swing.JTextField();
        notes = new javax.swing.JTextField();
        totalPrice = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        basicPrice = new javax.swing.JLabel();
        priceDisplay = new javax.swing.JLabel();
        basicPrice2 = new javax.swing.JLabel();
        itemName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.lightGray);

        itemCount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        itemCount.setModel(new javax.swing.SpinnerNumberModel());
        itemCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                itemCountStateChanged(evt);
            }
        });
        itemCount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCountMouseClicked(evt);
            }
        });
        itemCount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemCountPropertyChange(evt);
            }
        });
        itemCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemCountKeyPressed(evt);
            }
        });

        address.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        notes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        notes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesActionPerformed(evt);
            }
        });

        totalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalPrice.setText("Total=");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(84, 127, 206));
        jLabel7.setText("Notes (optional)");

        jButton2.setBackground(new java.awt.Color(84, 127, 206));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Order");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(84, 127, 206));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(84, 127, 206));
        jLabel8.setText("Address *");

        basicPrice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        basicPrice.setForeground(new java.awt.Color(84, 127, 206));
        basicPrice.setText("New Order");

        priceDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        priceDisplay.setText("Price=");

        basicPrice2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        basicPrice2.setForeground(new java.awt.Color(84, 127, 206));
        basicPrice2.setText("Item:");

        itemName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        itemName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basicPrice2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(itemName)
                                    .addGap(70, 70, 70)
                                    .addComponent(itemCount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(priceDisplay)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalPrice))
                                .addComponent(notes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(basicPrice)
                        .addGap(344, 344, 344))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicPrice)
                .addGap(47, 47, 47)
                .addComponent(basicPrice2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName)
                    .addComponent(itemCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceDisplay)
                    .addComponent(totalPrice))
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCountKeyPressed

    }//GEN-LAST:event_itemCountKeyPressed

    private void itemCountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemCountPropertyChange

    }//GEN-LAST:event_itemCountPropertyChange

    private void itemCountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCountMouseClicked

    }//GEN-LAST:event_itemCountMouseClicked

    private void itemCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_itemCountStateChanged
        this.totalPrice.setText("Total= Rs. "+(Integer.valueOf(price)*(int)itemCount.getValue()));
    }//GEN-LAST:event_itemCountStateChanged

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void notesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            JSONObject newOrder = new JSONObject();
            if( !(address.getText().equals("")) && (int)itemCount.getValue()!=0) {
                newOrder.put("status", "pending");
                newOrder.put("itemID", NewOrderInfo.getItemId());
                newOrder.put("shopId", NewOrderInfo.getShopId());
                newOrder.put("profileId", NewOrderInfo.getProfileId());
                newOrder.put("phoneNumber", NewOrderInfo.getPhoneNumber());
                newOrder.put("address", address.getText());
                newOrder.put("comments",notes.getText());
                newOrder.put("quantity",(int)itemCount.getValue());
                newOrder.put("category",NewOrderInfo.getCategory());
                JSONObject obj = NUSTANA.getClient().CreateObject("Orders", newOrder);
                UI.InfoMsg("Order successfully placed", "Success");
                this.dispose();
            }
            else{
                UI.ErrMsg("Address must be specified and order must be of alteast 1 item", "ERROR");
            }
    }//GEN-LAST:event_jButton2ActionPerformed
           catch(Exception e){
               UI.ErrMsg("Unable to place Order","Error");
           }
    }
    
    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel basicPrice;
    private javax.swing.JLabel basicPrice2;
    private javax.swing.JSpinner itemCount;
    private javax.swing.JLabel itemName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField notes;
    private javax.swing.JLabel priceDisplay;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
